spring:
  mail:
    host: smtp.qq.com
    username: 717626659@qq.com
    password: vcqoqjiganzwbedg
    default-encoding: UTF-8
    #使用SMTPS协议465端口
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true