prop:
  single: single  
  array: 1,2,3 
  list:
    - "1"
    - "2"
    - "3"
  map:
    "1": "1"
    "2": "2"
    "3": "3"
  map-list:  
    - "1": "1"
      "2": "2"
      "3": "3"
  list-map:
    "1":
      - "1"
      - "2"
      - "3"
  prop:
    name: name
    value: value